sudo: false

language: cpp

os:
  # - linux
  - osx

compiler:
  # - gcc
  - clang

script:
  - chmod +x build_mac.sh
  - ./build_mac.sh

deploy:
  provider: releases
  api_key:
    secure: "A+TbKzHk6ZIxWGJSpb7stM36Nx44G/BRfeNLDO2SpQMkZE19NZ9W2Uappb5ivB52Xh637pR/z2rWHwWqSKcAsM2hLCOpI3oAtZJQdFhOBPMoMTgiN9MZ6skaqbTimRXfOIbyGfewxuNiQDmQI9QK1rM3b1thnd81rBTAWprzDIo="
  file: kryvos_${TRAVIS_TAG}_mac.zip
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    recipients:
      - andrewdolby@gmail.com
    on_success: change
    on_failure: change
