sudo: required

language: generic

matrix:
  include:
    - os: osx
      compiler: clang
      env: CXX=clang++ CC=clang OSNAME=macos
    - os: linux
      compiler: clang
      env: CXX=clang++-3.9 CC=clang-3.9 OSNAME=linux
      addons:
        apt:
          packages:
            - clang-3.9
            - libc++-dev
          sources: &sources
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'

script:
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then chmod +x build_mac.sh ; fi
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then ./build_mac.sh ; fi
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then chmod +x build_linux.sh ; fi
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then ./build_linux.sh ; fi

deploy:
  provider: releases
  api_key:
    secure: "A+TbKzHk6ZIxWGJSpb7stM36Nx44G/BRfeNLDO2SpQMkZE19NZ9W2Uappb5ivB52Xh637pR/z2rWHwWqSKcAsM2hLCOpI3oAtZJQdFhOBPMoMTgiN9MZ6skaqbTimRXfOIbyGfewxuNiQDmQI9QK1rM3b1thnd81rBTAWprzDIo="
  file: kryvos_${TRAVIS_TAG}_${OSNAME}.zip
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    recipients:
      - andrewdolby@gmail.com
    on_success: change
    on_failure: change
