sudo: required

language: cpp

matrix:
  include:
    - os: osx
      compiler: clang
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6

script:
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then chmod +x build_mac.sh ; fi
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then ./build_mac.sh ; fi
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then chmod +x build_linux.sh ; fi
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then CXX="g++-6" CC="gcc-6" ./build_linux.sh ; fi

deploy:
  - provider: releases
    api_key:
      secure: "A+TbKzHk6ZIxWGJSpb7stM36Nx44G/BRfeNLDO2SpQMkZE19NZ9W2Uappb5ivB52Xh637pR/z2rWHwWqSKcAsM2hLCOpI3oAtZJQdFhOBPMoMTgiN9MZ6skaqbTimRXfOIbyGfewxuNiQDmQI9QK1rM3b1thnd81rBTAWprzDIo="
    file:
      - build/macx/clang/x86_64/release/kryvos_${TRAVIS_TAG}_macos.zip
    overwrite: true
    draft: true
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = osx
  - provider: releases
    api_key:
      secure: "A+TbKzHk6ZIxWGJSpb7stM36Nx44G/BRfeNLDO2SpQMkZE19NZ9W2Uappb5ivB52Xh637pR/z2rWHwWqSKcAsM2hLCOpI3oAtZJQdFhOBPMoMTgiN9MZ6skaqbTimRXfOIbyGfewxuNiQDmQI9QK1rM3b1thnd81rBTAWprzDIo="
    file:
      - build/linux/gcc/x86_64/release/kryvos_${TRAVIS_TAG}_linux_x86_64_portable.zip
      - installer/linux/kryvos_${TRAVIS_TAG}_linux_x86_64_installer
    overwrite: true
    draft: true
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux

notifications:
  email:
    recipients:
      - andrewdolby@gmail.com
    on_success: change
    on_failure: change
