image: Visual Studio 2015

environment:
  matrix:
  - QT: C:\Qt\5.7\msvc2015_64
    PLATFORM: amd64
    COMPILER: msvc
    VSVER: 14

clone_depth: 1

init:
  - set PATH=%QT%\bin;C:\Qt\Tools\QtCreator\bin;%PATH%

before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %PLATFORM%
  - cd src

build_script:
  - qmake -spec win32-msvc2015 CONFIG+=x86_64 CONFIG-=debug CONFIG+=release
  - nmake

after_build:
  - cd ..\build\win\msvc\x86_64\release\
  - windeployqt Kryvos.exe
  - rd /s /q moc
  - rd /s /q obj
  - rd /s /q qrc
  - cp "..\..\..\..\..\Release Notes" "Release Notes"
  - cp "..\..\..\..\..\README.md" "README.md"
  - cp "..\..\..\..\..\LICENSE" "LICENSE"
  - cp "..\..\..\..\..\Botan License" "Botan License"
  - cp "..\..\..\..\..\Qt License" "Qt License"
  - 7z a kryvos_%APPVEYOR_REPO_TAG_NAME%_win_x86_64.zip *

test_script:
  - cd ..\..\..\..\..\src\tests
  - qmake -spec win32-msvc2015 CONFIG+=x86_64 CONFIG-=debug CONFIG+=release
  - nmake
  - cd ..\..\build\win\msvc\x86_64\release\test\
  - CryptoTests

artifacts:
  - path: build\win\msvc\x86_64\release\kryvos_%APPVEYOR_REPO_TAG_NAME%_win_x86_64.zip
    name: kryvos

deploy:
  - provider: GitHub
    tag: $(appveyor_repo_tag_name)
    release: $(appveyor_repo_tag_name)
    description: $(appveyor_repo_tag_name)
    auth_token:
      secure: A+TbKzHk6ZIxWGJSpb7stM36Nx44G/BRfeNLDO2SpQMkZE19NZ9W2Uappb5ivB52Xh637pR/z2rWHwWqSKcAsM2hLCOpI3oAtZJQdFhOBPMoMTgiN9MZ6skaqbTimRXfOIbyGfewxuNiQDmQI9QK1rM3b1thnd81rBTAWprzDIo=
    artifact: kryvos
    draft: false
    prerelease: false
    force_update: true
    on:
      appveyor_repo_tag: true # deploy on tag push only
