image: Visual Studio 2015

environment:
  matrix:
  - QT: C:\Qt\5.7\msvc2015_64
    PLATFORM: amd64
    COMPILER: msvc
    VSVER: 14

clone_depth: 1

init:
  - set PATH=%QT%\bin;C:\Qt\Tools\QtCreator\bin;%PATH%

before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %PLATFORM%
  - cd src

build_script:
  - qmake -spec win32-msvc2015 CONFIG+=x86_64 CONFIG-=debug CONFIG+=release
  - nmake

test_script:
  - cd ..\..\..\..\..\src\tests
  - qmake -spec win32-msvc2015 CONFIG+=x86_64 CONFIG-=debug CONFIG+=release
  - nmake
  - cd ..\..\build\win\msvc\x86_64\release\test\
  - CryptoTests

after_build:
  - cd ..\build\win\msvc\x86_64\release\
  - windeployqt Kryvos.exe
  - rd /s /q moc
  - rd /s /q obj
  - rd /s /q qrc
  - cp "..\..\..\..\..\Release Notes" "Release Notes"
  - cp "..\..\..\..\..\README.md" "README.md"
  - cp "..\..\..\..\..\LICENSE" "LICENSE"
  - cp "..\..\..\..\..\Botan License" "Botan License"
  - cp "..\..\..\..\..\Qt License" "Qt License"
  - 7z a kryvos_%APPVEYOR_REPO_TAG_NAME%_win_x86_64.zip *

artifacts:
  - path: build\win\msvc\x86_64\release\kryvos_%APPVEYOR_REPO_TAG_NAME%_win_x86_64.zip
    name: kryvos

deploy:
  - provider: GitHub
    tag: $(appveyor_repo_tag_name)
    release: $(appveyor_repo_tag_name)
    description: $(appveyor_repo_tag_name)
    auth_token:
      secure: MBeWMiNMlHhvIoTe8XVy0kV8Aqzd79YqPjh6Bee7T6f2ERp+BnQKxuBex/Czp9iNAcXjsv1IURllbLdSoEf0x+9gmOb/WdNdDUyQFW9USR2RP6VPY01nZ59XkYcEInvzpi0Bzy/P8xzg6M13inCSBEX1KDVF73agYBb7Pkr2sM4=
    artifact: kryvos
    draft: false
    prerelease: false
    force_update: true
    on:
      appveyor_repo_tag: true # deploy on tag push only
