branches:
  only:
    - master

environment:
  matrix:
  # MSVC x86
  - name: win32
    platform: amd64_x86
    qt: 5.5\msvc2013
    suffix: msvc2013

  # MSVC x64
  - name: win64
    platform: amd64
    qt: 5.5\msvc2013_64
    suffix: msvc2013

  # MinGW
  # - name: win32
  #   platform: mingw
  #   qt: 5.5\mingw492_32
  #   suffix: mingw

before_build:
  - cd src

build_script:
  - if %platform%==mingw set PATH=C:\Qt\%qt%\bin;C:\Qt\Tools\mingw492_32\bin
  - qmake
  - if not %platform%==mingw (nmake) else (mingw32-make)

after_build:
  - if %platform%==amd64 (cd build/win/msvc/x86_64) else (cd build/win/msvc/x86)
  - windeployqt
  - if %platform%==amd64 (7z a kryvos_0.9.9_win_x86_64.zip *.*) else (7z a kryvos_0.9.9_win_x86.zip *.*)

test_script:
  - cd tests
  - qmake
  - if not %platform%==mingw (nmake) else (mingw32-make)
  - cd ../../build/macx/clang/x86_64/release/test/
  - CryptoTests.exe

artifacts:
- path: build
  name: kryvos_0.9.9_win_x86_64.zip
- path: build
    name: kryvos_0.9.9_win_x86.zip

deploy:
  release: v0.9.9
  description: 'v0.9.9'
  provider: GitHub
  auth_token:
    secure: MBeWMiNMlHhvIoTe8XVy0kV8Aqzd79YqPjh6Bee7T6f2ERp+BnQKxuBex/Czp9iNAcXjsv1IURllbLdSoEf0x+9gmOb/WdNdDUyQFW9USR2RP6VPY01nZ59XkYcEInvzpi0Bzy/P8xzg6M13inCSBEX1KDVF73agYBb7Pkr2sM4=
  artifact: kryvos_0.9.9_*.exe
  draft: false
  prerelease: true
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
