image: Visual Studio 2015

environment:
  matrix:
  - QT: C:\Qt\5.7\msvc2015
    PLATFORM: amd64_x86
    VSVER: 14
  - QT: C:\Qt\5.7\msvc2015_64
    PLATFORM: amd64
    VSVER: 14

clone_depth: 5

matrix:
  fast_finish: true

init:
  - echo %APPVEYOR_REPO_TAG_NAME%
  - set PATH=%QT%\bin;C:\Qt\Tools\QtCreator\bin;%PATH%

before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %PLATFORM%
  - cd src

build_script:
  - qmake
  - nmake

after_build:
  - if %PLATFORM%==amd64 (cd build/win/msvc/x86_64) else (cd build/win/msvc/x86)
  - windeployqt
  - if %PLATFORM%==amd64 (7z a kryvos-%APPVEYOR_REPO_TAG_NAME%_win_x86_64.zip *.*) else (7z a kryvos_%APPVEYOR_REPO_TAG_NAME%_win_x86.zip *.*)

test_script:
  - cd tests
  - qmake
  - nmake
  - cd ../../build/macx/clang/x86_64/release/test/
  - CryptoTests

artifacts:
  - path: build
    name: kryvos_$(appveyor_repo_tag_name)_win_x86_64.zip
  - path: build
    name: kryvos_$(appveyor_repo_tag_name)_win_x86.zip

deploy:
  - provider: GitHub
    release: $(appveyor_repo_tag_name)
    auth_token:
      secure: MBeWMiNMlHhvIoTe8XVy0kV8Aqzd79YqPjh6Bee7T6f2ERp+BnQKxuBex/Czp9iNAcXjsv1IURllbLdSoEf0x+9gmOb/WdNdDUyQFW9USR2RP6VPY01nZ59XkYcEInvzpi0Bzy/P8xzg6M13inCSBEX1KDVF73agYBb7Pkr2sM4=
    artifact: /.*\.zip/
    draft: false
    prerelease: false
    force_update: true
    on:
      appveyor_repo_tag: true # deploy on tag push only
