image: Visual Studio 2015

environment:
  matrix:
  - QT: C:\Qt\5.7\msvc2015_64
    PLATFORM: amd64
    COMPILER: msvc
    VSVER: 14

clone_depth: 1

init:
  - set PATH=%QT%\bin\;C:\Qt\Tools\QtCreator\bin\;C:\Qt\QtIFW2.0.1\bin\;%PATH%

before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %PLATFORM%
  - cd src

build_script:
  - qmake -spec win32-msvc2015 CONFIG+=x86_64 CONFIG-=debug CONFIG+=release
  - nmake

after_build:
  - cd ..
  - mkdir installer\windows\x64\packages\com.kryvosproject.kryvos\data\
  - cd build\win\msvc\x86_64\release\
  - windeployqt Kryvos.exe
  - rd /s /q moc
  - rd /s /q obj
  - rd /s /q qrc
  - cp "..\..\..\..\..\Release Notes" "Release Notes.txt"
  - cp "..\..\..\..\..\README.md" "README.md"
  - cp "..\..\..\..\..\LICENSE" "LICENSE.txt"
  - cp "..\..\..\..\..\Botan License" "Botan License.txt"
  - cp "..\..\..\..\..\Qt License" "Qt License.txt"
  - cp *.* ..\..\..\..\..\installer\windows\x64\packages\com.kryvosproject.kryvos\data\
  - mkdir Kryvos
  - cp *.* Kryvos\
  - 7z a kryvos_%APPVEYOR_REPO_TAG_NAME%_win_portable_x86_64.zip Kryvos
  - cd ..\..\..\..\..\installer\windows\x64\
  - binarycreator.exe --offline-only -c config\config.xml -p packages kryvos_%APPVEYOR_REPO_TAG_NAME%_win_installer_x86_64.exe

test_script:
  - cd ..\..\..\src\tests
  - qmake -spec win32-msvc2015 CONFIG+=x86_64 CONFIG-=debug CONFIG+=release
  - nmake
  - cd ..\..\build\win\msvc\x86_64\release\test\
  - CryptoTests

artifacts:
  - path: build\win\msvc\x86_64\release\kryvos_$(appveyor_repo_tag_name)_win_portable_x86_64.zip
    name: portable
  - path: installer\windows\x64\kryvos_$(appveyor_repo_tag_name)_win_installer_x86_64.exe
    name: installer

deploy:
  - provider: GitHub
    tag: $(appveyor_repo_tag_name)
    release: $(appveyor_repo_tag_name)
    description: $(appveyor_repo_tag_name)
    auth_token:
      secure: bOwrg0z7hv/7CnAQD2q+sf74q2vH40mWJLZYc8EzYvqkrXk9KYnd23rVCJ3Fsrqs
    artifact: portable, installer
    draft: true
    prerelease: false
    force_update: true
    on:
      appveyor_repo_tag: true # deploy on tag push only
