branches:
  except:
    - gh-pages

image: Visual Studio 2015

environment:
  matrix:
  # MSVC x86
  - name: win32
    platform: amd64_x86
    qt: 5.7\msvc2015
    suffix: msvc2015
    # MSVC x64
  - name: win64
    platform: amd64
    qt: 5.7\msvc2015_64
    suffix: msvc2015

matrix:
  fast_finish: true

init:
  - set PATH=C:\Qt\%qt%\bin;%PATH%

before_build:
  - cd src

build_script:
  - C:\Qt\%qt%\bin\qmake
  - nmake

after_build:
  - if %platform%==amd64 (cd build/win/msvc/x86_64) else (cd build/win/msvc/x86)
  - windeployqt
  - if %platform%==amd64 (7z a kryvos-0.9.9_win_x86_64.zip *.*) else (7z a kryvos_0.9.9_win_x86.zip *.*)

test_script:
  - cd tests
  - C:\Qt\%qt%\bin\qmake
  - if not %platform%==mingw (nmake) else (mingw32-make)
  - cd ../../build/macx/clang/x86_64/release/test/
  - CryptoTests

artifacts:
- path: build
  name: kryvos_0.9.9_win_x86_64.zip
- path: build
  name: kryvos_0.9.9_win_x86.zip

deploy:
  release: v0.9.9
  description: 'v0.9.9'
  provider: GitHub
  auth_token:
    secure: MBeWMiNMlHhvIoTe8XVy0kV8Aqzd79YqPjh6Bee7T6f2ERp+BnQKxuBex/Czp9iNAcXjsv1IURllbLdSoEf0x+9gmOb/WdNdDUyQFW9USR2RP6VPY01nZ59XkYcEInvzpi0Bzy/P8xzg6M13inCSBEX1KDVF73agYBb7Pkr2sM4=
  artifact: /.*\.zip/
  draft: false
  prerelease: false
  force_update: true
  on:
    branch: master
    appveyor_repo_tag: true # deploy on tag push only
