image: Visual Studio 2017

environment:
  matrix:
  - QTPATH: C:\Qt\5.12.1\msvc2017_64
    PLATFORM: amd64
    COMPILER: msvc
    VSVER: 15

clone_depth: 1

init:
  - set TAG_NAME=%APPVEYOR_REPO_TAG_NAME%

build_script:
  - call "build_windows_msvc.cmd"

artifacts:
  - path: build\windows\msvc\x86_64\release\kryvo_$(appveyor_repo_tag_name)_windows_x86_64_portable.zip
    name: portable
  - path: installer\windows\x86_64\kryvo_$(appveyor_repo_tag_name)_windows_x86_64_installer.exe
    name: installer

deploy:
  - provider: GitHub
    tag: $(appveyor_repo_tag_name)
    release: $(appveyor_repo_tag_name)
    description: $(appveyor_repo_tag_name)
    auth_token:
      secure: bOwrg0z7hv/7CnAQD2q+sf74q2vH40mWJLZYc8EzYvqkrXk9KYnd23rVCJ3Fsrqs
    artifact: portable, installer
    draft: false
    prerelease: false
    force_update: true
    on:
      branch: master
      appveyor_repo_tag: true # deploy on tag push only
