name: Linux Release

on:
  push:
    tags:
      - 'v*'

defaults:
  run:
    shell: bash

env:
  SOURCE_DIR: ${{ github.workspace }}
  QT_VERSION: 6.4.2
  TAG_NAME: ${{ github.ref_name }}

jobs:
  build:
    runs-on:  ubuntu-latest

    steps:
      - name: (1) Checkout repo
        uses: actions/checkout@v3

      - name: (2) Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ env.QT_VERSION }}
          host: linux
          target: desktop
          arch: gcc_64
          tools: tools_ifw
          cache: true

      - name: (3) Install extra Linux dependencies
        run: |
          sudo apt-get -qq install chrpath
          sudo apt-get -qq install libxkbcommon-x11-0

      - name: (4) Build
        working-directory: ${{ env.SOURCE_DIR }}
        run: |
          cd "${{ env.SOURCE_DIR }}"
          chmod +x build_linux_ci.sh
          ./build_linux_ci.sh

      - name: (5) Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: "kryvo_${{ env.TAG_NAME }}_linux_x86_64_portable.tar.gz"
          path: "${{ env.SOURCE_DIR }}/build/linux/gcc/x86_64/release/kryvo_${{ env.TAG_NAME }}_linux_x86_64_portable.tar.gz"

      - name: (6) Create release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
          files: |
            "${{ env.SOURCE_DIR }}/build/linux/gcc/x86_64/release/kryvo_${{ env.TAG_NAME }}_linux_x86_64_portable.tar.gz"
            "${{ env.SOURCE_DIR }}/installer/linux/x86_64/kryvo_${{ env.TAG_NAME }}_linux_x86_64_installer"
