name: Linux Develop

on:
  push:
    branches:
      - 'develop'
  pull_request:
    branches:
      - 'develop'

defaults:
  run:
    shell: bash

env:
  SOURCE_DIR: ${{ github.workspace }}
  QT_VERSION: 6.5.0

jobs:
  build:
    runs-on:  ubuntu-latest

    steps:
      - name: (1) Checkout repo
        uses: actions/checkout@v3

      - name: (2) Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==3.1.*'
          py7zrversion: '>=0.20.2'
          version: ${{ env.QT_VERSION }}
          host: linux
          target: desktop
          arch: gcc_64
          cache: true
          tools: 'tools_ifw'

      - name: (3) Install extra Linux dependencies
        run: |
          sudo apt-get -qq install chrpath
          sudo apt-get -qq install libxkbcommon-x11-0
          sudo apt-get -qq install libssl-dev

      - name: (4) Get short SHA for artifact naming
        run: echo "KRYVO_VERSION=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: (5) Build
        working-directory: ${{ env.SOURCE_DIR }}
        run: |
          cd "${{ env.SOURCE_DIR }}"
          chmod +x build_linux_ci.sh
          ./build_linux_ci.sh

      - name: (6) Save build artifact
        uses: actions/upload-artifact@v3
        with:
          name: "kryvo_${{ env.KRYVO_VERSION }}_linux_x86_64_portable.tar.gz"
          path: "${{ env.SOURCE_DIR }}/build/linux/gcc/x86_64/release/kryvo_${{ env.KRYVO_VERSION }}_linux_x86_64_portable.tar.gz"
