name: macOS Release

on:
  push:
    tags:
      - 'v*'

defaults:
  run:
    shell: bash

env:
  SOURCE_DIR: ${{ github.workspace }}
  QT_VERSION: 6.4.2
  TAG_NAME: ${{ github.ref_name }}

jobs:
  build:
    runs-on:  macos-latest

    steps:
      - name: (1) Checkout repo
        uses: actions/checkout@v3

      - name: (2) Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ env.QT_VERSION }}
          host: mac
          target: desktop
          arch: clang_64
          cache: true

      - name: (3) Build
        working-directory: ${{ env.SOURCE_DIR }}
        run: |
          cd "${{ env.SOURCE_DIR }}"
          chmod +x build_macOS_ci.sh
          ./build_macOS_ci.sh

      - name: (4) Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: "kryvo_${{ env.TAG_NAME }}_macos.tar.gz"
          path: "${{ env.SOURCE_DIR }}/build/macOS/clang/x86_64/release/kryvo_${{ env.TAG_NAME }}_macos.tar.gz"

       - name: (5) Create release
         uses: softprops/action-gh-release@v1
         with:
           draft: false
           prerelease: false
           fail_on_unmatched_files: true
           files: |
             "${{ env.SOURCE_DIR }}/build/macOS/clang/x86_64/release/kryvo_${{ env.TAG_NAME }}_macos.tar.gz"
