name: Windows Release

on:
  push:
    branches:
      - 'main'
      - 'feat/githubActions'
    tags:
      - 'v*'
  pull_request:
    branches:
    - 'main'

defaults:
  run:
    shell: cmd

env:
  SOURCE_DIR: ${{ github.workspace }}
  REF_NAME: ${{ github.ref_name }}
  REF_TYPE: ${{ github.ref_type }}
  ARCH: amd64
  QT_VERSION: 6.4.2

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: (0) Sets env vars for tag ref
        run: |
          echo "TAG_NAME=%REF_NAME%" >> $env:GITHUB_ENV
        if: ${{ env.REF_TYPE }}=="tag"

      - name: (0) Sets env var for branch ref
        run: |
          echo "TAG_NAME=dev" >> $env:GITHUB_ENV
        if: ${{ env.REF_TYPE }}=="branch"

      - name: (1) Checkout repo
        uses: actions/checkout@v3

      - name: (2) Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ env.QT_VERSION }}
          host: windows
          target: desktop
          arch: win64_msvc2019_64
          tools: tools_ifw
          cache: true
          dir: ${{ runner.temp }}

      - name: (3) Build
        working-directory: ${{ github.workspace }}
        run: call "${{ env.SOURCE_DIR }}\build_windows_msvc.cmd"

      - name: (4) Save build artifact
        uses: actions/upload-artifact@v3
        with:
          name: "kryvo_${{ env.TAG_NAME }}_windows_x86_64_portable.zip"
          path: "${{ env.SOURCE_DIR }}\\build\\windows\\msvc\\x86_64\\release\\kryvo_${{ env.TAG_NAME }}_windows_x86_64_portable.zip"
