name: Windows Release

on:
  push:
    branches:
      - 'main'
      - 'feat/githubActions'
    tags:
      - 'v*'
  pull_request:
    branches:
    - 'main'

defaults:
  run:
    shell: cmd

env:
  SOURCE_DIR: ${{ github.workspace }}
  QT_VERSION: 6.4.2

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: (1) Checkout repo
        uses: actions/checkout@v3

      - name: (2) Get all tags for correct version determination
        working-directory: ${{ github.workspace }}
        run:
          git fetch --all --tags -f

      - name: (3) Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ env.QT_VERSION }}
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          tools: 'tools_ifw'
          cache: true
          dir: ${{ runner.temp }}

      - name: (4) Create build directory
        run:  mkdir ${{ runner.temp }}\build

      - name: (5) Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - name: (8) Build
        working-directory: ${{ runner.temp }}\build
        run:
          call "${{ env.SOURCE_DIR }}\build_windows_msvc.cmd"

      # - name: (9) Zip build
      #   working-directory: ${{ runner.temp }}
      #   run:  |
      #         7z a qt-planets-build.zip ${{ runner.temp }}\build\* -r

      # - name: (10) Save build artifact
      #   uses: actions/upload-artifact@master
      #   with:
      #     name: ${{ env.ARTIFACT }}
      #     path: ${{ runner.temp }}\${{ env.ARTIFACT }}
